branch-defaults:
  develop:
    environment: null
  master:
    environment: creative-failure-prod
    group_suffix: null
global:
  application_name: creative_failure
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  profile: creative-failure
  sc: git
